config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :nakladatelstvi
  resources :zanry
  resources :autori
  resources :knihy
  resources :main, only: :index
  resources :technika, only: :index
  resources :datove_nosice, only: :index
  resources :sbirky, only: :index

  root to: 'main#index'

  resources :user_sessions

  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<table align="center" style="border-collapse: collapse; vertical-align: center;">
  <tr>
    <td width="200px" class="oramovat"><%= link_to 'TECHNIKA', technika_index_path %></td>
    <td width="50px"></td>
    <td width="200px"></td>
    <td width="50px"></td>
    <td width="200px" class="oramovat"><%= link_to 'KNIHOVNA', knihy_path %></td>
  </tr>
  <tr>
    <td></td>
    <td colspan="3" class="oramovat">MEGASUPER</td>
    <td></td>
  </tr>
  <tr>
    <td class="oramovat">HJP</td>
    <td class="oramovat"></td>
    <td class="oramovat">MSB</td>
    <td class="oramovat"></td>
    <td class="oramovat">HJP</td>
  </tr>
  <tr>
    <td></td>
    <td colspan="3" class="oramovat">BASE</td>
    <td></td>
  </tr>
  <tr>
    <td class="oramovat"><%= link_to 'DATOVÉ NOSIČE', datove_nosice_index_path %></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="oramovat"><%= link_to 'SBÍRKY', sbirky_index_path %></td>
  </tr>
</table>