config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :nakladatelstvi
  resources :zanry
  resources :autori
  resources :knihy
  resources :main, only: :index
  resources :technika, only: :index
  resources :datove_nosice, only: :index
  resources :sbirky, only: :index

  root to: 'main#index'

  resources :user_sessions

  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/knihy_controller.rb
class KnihyController < ApplicationController
  before_action :set_kniha, only: [:show, :edit, :update, :destroy]

  # GET /knihy
  # GET /knihy.json
  def index
    @knihy = Kniha.all
  end

  # GET /knihy/1
  # GET /knihy/1.json
  def show
  end

  # GET /knihy/new
  def new
    @kniha = Kniha.new
  end

  # GET /knihy/1/edit
  def edit
  end

  # POST /knihy
  # POST /knihy.json
  def create
    @kniha = Kniha.new(kniha_params)

    respond_to do |format|
      if @kniha.save
        format.html { redirect_to @kniha, notice: 'Kniha was successfully created.' }
        format.json { render :show, status: :created, location: @kniha }
      else
        format.html { render :new }
        format.json { render json: @kniha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knihy/1
  # PATCH/PUT /knihy/1.json
  def update
    respond_to do |format|
      if @kniha.update(kniha_params)
        format.html { redirect_to @kniha, notice: 'Kniha was successfully updated.' }
        format.json { render :show, status: :ok, location: @kniha }
      else
        format.html { render :edit }
        format.json { render json: @kniha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knihy/1
  # DELETE /knihy/1.json
  def destroy
    @kniha.destroy
    respond_to do |format|
      format.html { redirect_to knihy_url, notice: 'Kniha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kniha
      @kniha = Kniha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kniha_params
      params.require(:kniha).permit(:nazev, :autor_id, :zanr_id, :isbn, :nakladatelstvi_id, :pocet_stran, :vydani, :rozmer, :rok_vydani, :vazba, :cena, :poznamka, :popis, :koupeno, :ziskano)
    end
end

app/helpers/knihy_helper.rb
module KnihyHelper
end

app/views/knihy/_form.html.erb
<%= form_with(model: kniha, local: true) do |form| %>
  <% if kniha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kniha.errors.count, "error") %> prohibited this kniha from being saved:</h2>

      <ul>
      <% kniha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nazev %>
    <%= form.text_field :nazev, id: :kniha_nazev %>
  </div>

  <div class="field">
    <%= form.label :autor_id %>
    <%= form.select :autor_id, Autor.all.collect { |p| [ p.cele_jmeno, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :zanr_id %>
    <%= form.select :zanr_id, Zanr.all.collect { |p| [ p.nazev, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, id: :kniha_isbn %>
  </div>

  <div class="field">
    <%= form.label :nakladatelstvi_id %>
    <%= form.select :nakladatelstvi_id, Nakladatelstvi.all.collect { |p| [ p.nazev, p.id ] }, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :pocet_stran %>
    <%= form.number_field :pocet_stran, id: :kniha_pocet_stran %>
  </div>

  <div class="field">
    <%= form.label :vydani %>
    <%= form.text_field :vydani, id: :kniha_vydani %>
  </div>

  <div class="field">
    <%= form.label :rozmer %>
    <%= form.text_field :rozmer, id: :kniha_rozmer %>
  </div>

  <div class="field">
    <%= form.label :rok_vydani %>
    <%= form.text_field :rok_vydani, id: :kniha_rok_vydani %>
  </div>

  <div class="field">
    <%= form.label :vazba %>
    <%= form.text_field :vazba, id: :kniha_vazba %>
  </div>

  <div class="field">
    <%= form.label :cena %>
    <%= form.text_field :cena, id: :kniha_cena %>
  </div>

  <div class="field">
    <%= form.label :poznamka %>
    <%= form.text_field :poznamka, id: :kniha_poznamka %>
  </div>

  <div class="field">
    <%= form.label :popis %>
    <%= form.text_area :popis, id: :kniha_popis %>
  </div>

  <div class="field">
    <%= form.label :koupeno %>
    <%= form.check_box :koupeno, id: :kniha_koupeno %>
  </div>

  <div class="field">
    <%= form.label :ziskano %>
    <%= form.check_box :ziskano, id: :kniha_ziskano %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/knihy/edit.html.erb
<h1>Editing Kniha</h1>

<%= render 'form', kniha: @kniha %>

<%= link_to 'Show', @kniha %> |
<%= link_to 'Back', knihy_path %>

app/views/knihy/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Knihy</h1>
<%= link_to 'Autoři', autori_path %>
<%= link_to 'Žánry', zanry_path %>
<%= link_to 'Nakladatelství', nakladatelstvi_index_path %>

<table>
  <thead>
    <tr>
      <th>Nazev</th>
      <th>Autor</th>
      <th>Zanr</th>
      <th>Isbn</th>
      <th>Nakladatelstvi</th>
      <th>Pocet stran</th>
      <th>Vydani</th>
      <th>Rozmer</th>
      <th>Rok vydani</th>
      <th>Vazba</th>
      <th>Cena</th>
      <th>Poznamka</th>
      <th>Koupeno</th>
      <th>Ziskano</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @knihy.each do |kniha| %>
      <tr>
        <td><%= kniha.nazev %></td>
        <td><%= kniha.jmeno_autora %></td>
        <td><%= kniha.nazev_zanru %></td>
        <td><%= kniha.isbn %></td>
        <td><%= kniha.nazev_nakladatelstvi %></td>
        <td><%= kniha.pocet_stran %></td>
        <td><%= kniha.vydani %></td>
        <td><%= kniha.rozmer %></td>
        <td><%= kniha.rok_vydani %></td>
        <td><%= kniha.vazba %></td>
        <td><%= kniha.cena %></td>
        <td><%= kniha.poznamka %></td>
        <td><%= kniha.koupeno %></td>
        <td><%= kniha.ziskano %></td>
        <td><%= link_to 'Show', kniha %></td>
        <td><%= link_to 'Edit', edit_kniha_path(kniha) %></td>
        <td><%= link_to 'Destroy', kniha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kniha', new_kniha_path %>

<p><%= link_to 'Hlavní', main_index_path %></p>

app/views/knihy/new.html.erb
<h1>New Kniha</h1>

<%= render 'form', kniha: @kniha %>

<%= link_to 'Back', knihy_path %>

app/views/knihy/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazev:</strong>
  <%= @kniha.nazev %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @kniha.jmeno_autora %>
</p>

<p>
  <strong>Zanr:</strong>
  <%= @kniha.nazev_zanru %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @kniha.isbn %>
</p>

<p>
  <strong>Nakladatelstvi:</strong>
  <%= @kniha.nazev_nakladatelstvi %>
</p>

<p>
  <strong>Pocet stran:</strong>
  <%= @kniha.pocet_stran %>
</p>

<p>
  <strong>Vydani:</strong>
  <%= @kniha.vydani %>
</p>

<p>
  <strong>Rozmer:</strong>
  <%= @kniha.rozmer %>
</p>

<p>
  <strong>Rok vydani:</strong>
  <%= @kniha.rok_vydani %>
</p>

<p>
  <strong>Vazba:</strong>
  <%= @kniha.vazba %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @kniha.cena %>
</p>

<p>
  <strong>Poznamka:</strong>
  <%= @kniha.poznamka %>
</p>

<p>
  <strong>Popis:</strong>
  <%= @kniha.popis %>
</p>

<p>
  <strong>Koupeno:</strong>
  <%= @kniha.koupeno %>
</p>

<p>
  <strong>Ziskano:</strong>
  <%= @kniha.ziskano %>
</p>

<%= link_to 'Edit', edit_kniha_path(@kniha) %> |
<%= link_to 'Back', knihy_path %>