config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :nakladatelstvi
  resources :zanry
  resources :autori
  resources :knihy
  resources :main, only: :index
  resources :technika, only: :index
  resources :datove_nosice, only: :index
  resources :sbirky, only: :index

  root to: 'main#index'

  resources :user_sessions

  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nakladatelstvi.rb
# == Schema Information
#
# Table name: nakladatelstvi
#
#  id         :integer          not null, primary key
#  nazev      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Nakladatelstvi < ApplicationRecord
  has_many :knihy
end

app/controllers/nakladatelstvi_controller.rb
class NakladatelstviController < ApplicationController
  before_action :set_nakladatelstvi, only: [:show, :edit, :update, :destroy]

  # GET /nakladatelstvi
  # GET /nakladatelstvi.json
  def index
    @nakladatelstvi = Nakladatelstvi.all
  end

  # GET /nakladatelstvi/1
  # GET /nakladatelstvi/1.json
  def show
  end

  # GET /nakladatelstvi/new
  def new
    @nakladatelstvi = Nakladatelstvi.new
  end

  # GET /nakladatelstvi/1/edit
  def edit
  end

  # POST /nakladatelstvi
  # POST /nakladatelstvi.json
  def create
    @nakladatelstvi = Nakladatelstvi.new(nakladatelstvi_params)

    respond_to do |format|
      if @nakladatelstvi.save
        format.html { redirect_to nakladatelstvi_index_path, notice: 'Nakladatelstvi was successfully created.' }
        format.json { render :show, status: :created, location: @nakladatelstvi }
      else
        format.html { render :new }
        format.json { render json: @nakladatelstvi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nakladatelstvi/1
  # PATCH/PUT /nakladatelstvi/1.json
  def update
    respond_to do |format|
      if @nakladatelstvi.update(nakladatelstvi_params)
        format.html { redirect_to nakladatelstvi_index_path, notice: 'Nakladatelstvi was successfully updated.' }
        format.json { render :show, status: :ok, location: @nakladatelstvi }
      else
        format.html { render :edit }
        format.json { render json: @nakladatelstvi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nakladatelstvi/1
  # DELETE /nakladatelstvi/1.json
  def destroy
    @nakladatelstvi.destroy
    respond_to do |format|
      format.html { redirect_to nakladatelstvi_index_url, notice: 'Nakladatelstvi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nakladatelstvi
      @nakladatelstvi = Nakladatelstvi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nakladatelstvi_params
      params.require(:nakladatelstvi).permit(:nazev)
    end
end

app/helpers/nakladatelstvi_helper.rb
module NakladatelstviHelper
end

app/views/nakladatelstvi/_form.html.erb
<%= form_with(model: nakladatelstvi, local: true) do |form| %>
  <% if nakladatelstvi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nakladatelstvi.errors.count, "error") %> prohibited this nakladatelstvi from being saved:</h2>

      <ul>
      <% nakladatelstvi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nazev %>
    <%= form.text_field :nazev, id: :nakladatelstvi_nazev %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nakladatelstvi/edit.html.erb
<h1>Editing Nakladatelstvi</h1>

<%= render 'form', nakladatelstvi: @nakladatelstvi %>

<%= link_to 'Show', @nakladatelstvi %> |
<%= link_to 'Back', nakladatelstvi_index_path %>

app/views/nakladatelstvi/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nakladatelstvi</h1>

<table>
  <thead>
    <tr>
      <th>Nazev</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nakladatelstvi.each do |nakladatelstvi| %>
      <tr>
        <td><%= nakladatelstvi.nazev %></td>
        <td><%= link_to 'Show', nakladatelstvi %></td>
        <td><%= link_to 'Edit', edit_nakladatelstvi_path(nakladatelstvi) %></td>
        <td><%= link_to 'Destroy', nakladatelstvi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nakladatelstvi', new_nakladatelstvi_path %>

<p><%= link_to 'Hlavní', main_index_path %></p>
<p><%= link_to 'Knihovna', knihy_path %></p>

app/views/nakladatelstvi/new.html.erb
<h1>New Nakladatelstvi</h1>

<%= render 'form', nakladatelstvi: @nakladatelstvi %>

<%= link_to 'Back', nakladatelstvi_index_path %>

app/views/nakladatelstvi/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nazev:</strong>
  <%= @nakladatelstvi.nazev %>
</p>

<%= link_to 'Edit', edit_nakladatelstvi_path(@nakladatelstvi) %> |
<%= link_to 'Back', nakladatelstvi_index_path %>